package com.example.ChatMap.Controllers;

import java.util.Map;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.security.authentication.AuthenticationManager;

import com.example.ChatMap.Dto.LoginRequest;
import com.example.ChatMap.Dto.SignupRequest;
import com.example.ChatMap.Dto.UserResponse;
import com.example.ChatMap.Entities.User;
import com.example.ChatMap.Repositories.UserRepository;
import com.example.ChatMap.Services.CustomUserDetailsService;
import com.example.ChatMap.Utils.JwtUtil;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/users") // This means URL's start with /demo (after Application path)
@RestController
public class UserController {

	@Autowired
	private AuthenticationManager authenticationManager;

	@Autowired
	private CustomUserDetailsService userDetailsService;

	@Autowired
	private PasswordEncoder passwordEncoder;

	@Autowired
	private JwtUtil jwtUtil;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping("/signup")
	public ResponseEntity<?> registerUser(@RequestBody SignupRequest signupRequest) {

		User user = new User();

		// Encode the user's password
		user.setUsername(signupRequest.getUsername());
		user.setEmail(signupRequest.getEmail());
		user.setPassword(passwordEncoder.encode(signupRequest.getPassword()));

		userRepository.save(user);

		final UserDetails userDetails = userDetailsService.loadUserByUsername(signupRequest.getUsername());

		final Integer userId = userRepository.findIdByUsername(userDetails.getUsername());

		final String jwt = jwtUtil.generateToken(userId);

		// Save the user to the database

		return ResponseEntity.ok(Map.of("jwt", jwt, "expires", jwtUtil.extractExpiration(jwt), "userId", userId,
				"username", userDetails.getUsername()));
	}

	@PostMapping(path = "/login")
	public @ResponseBody ResponseEntity<?> login(@RequestBody LoginRequest loginRequest) throws Exception {

		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(loginRequest.getUsername(), loginRequest.getPassword()));

		final UserDetails userDetails = userDetailsService.loadUserByUsername(loginRequest.getUsername());

		final Integer userId = userRepository.findIdByUsername(userDetails.getUsername());

		final String jwt = jwtUtil.generateToken(userId);

		return ResponseEntity.ok(Map.of("jwt", jwt, "expires", jwtUtil.extractExpiration(jwt), "userId", userId,
				"username", userDetails.getUsername()));
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path = "/{id}")
	public @ResponseBody ResponseEntity<?> getUserById(@PathVariable("id") Integer id) {
		final Optional<User> userExists = userRepository.findById(id);
		if (userExists.isPresent()) {

			final User user = userExists.get();
			final UserResponse userResponse = new UserResponse(user.getId(), user.getUsername(), user.getEmail());
			return ResponseEntity.ok(userResponse);
		} else {
			return ResponseEntity.notFound().build();
		}

	}

}
