package com.example.ChatMap.Controllers;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.security.authentication.AuthenticationManager;

import com.example.ChatMap.Entities.User;
import com.example.ChatMap.Model.AuthenticationRequest;
import com.example.ChatMap.Repositories.UserRepository;
import com.example.ChatMap.Services.CustomUserDetailsService;
import com.example.ChatMap.Utils.JwtUtil;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/users") // This means URL's start with /demo (after Application path)
@RestController
public class UserController {

	@Autowired
	private AuthenticationManager authenticationManager;

	@Autowired
	private CustomUserDetailsService userDetailsService;

	@Autowired
	private PasswordEncoder passwordEncoder;

	@Autowired
	private JwtUtil jwtUtil;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email,
			@RequestParam String password) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		n.setPassword(password);
		userRepository.save(n);
		return "Saved";
	}

	@PostMapping("/signup")
	public ResponseEntity<?> registerUser(@RequestBody User user) {
		// Encode the user's password

		user.setPassword(passwordEncoder.encode(user.getPassword()));
		// Save the user to the database
		userRepository.save(user);
		return ResponseEntity.ok(null);
	}

	@PostMapping(path = "/login")
	public @ResponseBody ResponseEntity<?> login(@RequestBody AuthenticationRequest authenticationRequest)
			throws Exception {
		System.out.println(authenticationRequest.toString());
		authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(authenticationRequest.getUsername(),
				authenticationRequest.getPassword()));

		final UserDetails userDetails = userDetailsService.loadUserByUsername(authenticationRequest.getUsername());
		final String jwt = jwtUtil.generateToken(userDetails);
		final Integer userId = userRepository.findIdByUsername(userDetails.getUsername());

		return ResponseEntity.ok(Map.of("jwt", jwt, "expires", jwtUtil.extractExpiration(jwt), "userId", userId));
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<User> getAllUsers(CsrfToken token) {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping("/csrf/token")
	public CsrfToken csrf(CsrfToken token) {
		return token;
	}
	@GetMapping("/hellow")
	public @ResponseBody ResponseEntity<Map<String, String>> hellow() {
		return ResponseEntity.ok(Map.of("message","hellow"));
	}

}
